### ISSUE TITLE
Expose cuMemcpyDtoH_v2 in cust

### ISSUE THREAD

**Issue by kjetilkjeka** [Rust-GPU/Rust-CUDA#45]
In the latest version (`0.3.0`) of cust `cuMemcpyHtoD_v2` was exposed as `cust::memory::memcpy_htod`. This avoids the need for reaching into `cust_raw` and allows using `cust::error::CudaResult` instead of error codes.

Should `cuMemcpyDtoH_v2` be exposed in a similar manner to enable the features above for device to host memcpy as well?

**Comment by RDambrosio016** [comment]
Yeah it should be for consistency
