### ISSUE TITLE
libnvvm.so not found

### ISSUE THREAD

**Issue by jafioti** [Rust-GPU/Rust-CUDA#78]
I'm following the add example, and I get to the last step, but when I build, I get this:
`cuda_test/cuda_runner/target/debug/build/cuda_runner-170008ea0ebbe57c/build-script-build: error while loading shared libraries: libnvvm.so.4: cannot open shared object file: No such file or directory`

As far as I can tell, libnvvm.so is in cuda, which should be found by rustcuda. Is there any env variable I need to set, or any place I need to copy libnvvm.so?

**Comment by jafioti** [comment]
Nevermind, I fixed it by adding the folder containing libnvvm.so to my LD_LIBRARY_PATH

**Comment by brandonros** [comment]
```shell
find /usr/local/cuda/lib64/ /usr/local/cuda/nvvm/lib64/ /usr/lib/x86_64-linux-gnu/ /usr/lib/nvidia-cuda-toolkit/ /usr/lib/cuda/nvvm/lib64/ -type f -name "*libnvvm*" 2>/dev/null
/usr/local/cuda/nvvm/lib64/libnvvm.so.4.0.0
export LD_LIBRARY_PATH="/usr/local/cuda/nvvm/lib64/"
```
