### ISSUE TITLE
Installing llvm 7 on Ubuntu 22.04

### ISSUE THREAD

**Issue by jafioti** [Rust-GPU/Rust-CUDA#79]
I'm currently running Ubuntu 22.04 and have had quite a bit of trouble getting llvm installed. It seems it's not supported anymore, and 20.04 was the last version that supported it. Given  22.04 is the newest LTS version, and llvm 7 is required for this project to work, this seems like a massive problem. Am I missing some more straightforward way of installing this?

**Comment by kjetilkjeka** [comment]
Is this a duplicate of #23 ?

**Comment by jafioti** [comment]
@kjetilkjeka  I believe so, will lose. Hope this gets solved sooner or later.
