### ISSUE TITLE
Requesting help for updating Rust-CUDA to newer rustc version.

### ISSUE THREAD

**Issue by apriori** [Rust-GPU/Rust-CUDA#95]
Hello everyone. It has been quite a while till the `rust-toolchain` has been updated. I've been trying to to get something up, but am kind of stuck due to lack of knowledge about the rustc codegen API. Can someone maybe take a look at my fork at https://github.com/apriori/Rust-CUDA/tree/update-to-latest-nightly and assist in its completion?

**Comment by thedodd** [comment]
Definitely a great idea to get the toolchain updated!

**Comment by apriori** [comment]
The port compiles, however. Codegen does not seem to be working yet. Maybe someone of you can give it a try and also investigate. Make sure to get rid of `register_attr` in your gpu code as the feature has been dropped from rustc and is replaced with a scoped replacement `register_tool` that also requires a trampoline macro  as shown in [rust-gpu:c3a9b](https://github.com/EmbarkStudios/rust-gpu/commit/c3a9b9fd3e18cc7fd78a85dedbc4b77461d1ab05).
My fork injects the `no_std` and `register_tool` via rustc flags in`cudabuilder`, however, one still requires a `use cuda_std::nvmm_internal`.

**Comment by apriori** [comment]
I opened https://github.com/Rust-GPU/Rust-CUDA/pull/98. `add_gpu` is working in that state now. Further discussion should continue there.
